### ISSUE TITLE
Experiment with macOS 11.0+ support

### ISSUE THREAD

**Issue by afastaudir8** [y08wilm/Semaphorin#21]

**Comment by afastaudir8** [comment]
# macOS 11.0+ support

As it currently stands, Semaphorin **fully works** with macOS 14.4.1. Additional testing would be required, but from my testing, **no changes** are needed. 

### If you're able to, please test this script on macOS versions 11.0 Big Sur and newer and report the results back to me on Discord (afastaudir8) or in the [Discord server](https://discord.gg/WQWDBBYJTb).

As always, when experimenting with things like this, **absolutely no support will be given if you're using this on macOS 11+**

**Comment by afastaudir8** [comment]
On macOS Monterey, someone got iOS 11.1 to work. The issue is that iOS 10.3.3 never got past booting the SSH ramdisk. This is worth looking into.

**Comment by y08wilm** [comment]
confirmed working all the way up to sonoma. the issues people were having were usb issues
